from __future__ import annotations

import argparse
import ipaddress
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

from .common import activate_generated_file, env_bool, exclusive_lock


DEFAULT_INSTALL_DIR = Path(os.getenv("DNSDIST_INSTALL_DIR", "/opt/mydnsdist"))
DEFAULT_TARGET = DEFAULT_INSTALL_DIR / "generated/ecs-rules.lua"
DEFAULT_MAIN_CONFIG = DEFAULT_INSTALL_DIR / "config/dnsdist.conf"
DEFAULT_LOCK = DEFAULT_INSTALL_DIR / "generated/.ecs-update.lock"


@dataclass(frozen=True)
class PeerMapping:
    source: ipaddress.IPv4Network | ipaddress.IPv6Network
    ecs: ipaddress.IPv4Network | ipaddress.IPv6Network
    public_key: str


def parse_endpoint_ip(endpoint: str) -> ipaddress.IPv4Address | ipaddress.IPv6Address | None:
    value = endpoint.strip()
    if not value or value == "(none)":
        return None
    if value.startswith("["):
        closing = value.find("]")
        if closing < 0:
            return None
        host = value[1:closing]
    else:
        if ":" not in value:
            return None
        host = value.rsplit(":", 1)[0]
    try:
        return ipaddress.ip_address(host)
    except ValueError:
        return None


def endpoint_to_ecs(
    address: ipaddress.IPv4Address | ipaddress.IPv6Address,
    *,
    prefix_v4: int = 32,
    prefix_v6: int = 128,
) -> ipaddress.IPv4Network | ipaddress.IPv6Network:
    prefix = prefix_v4 if address.version == 4 else prefix_v6
    return ipaddress.ip_network(f"{address}/{prefix}", strict=False)


def parse_wg_dump(
    text: str,
    wg_network: ipaddress.IPv4Network | ipaddress.IPv6Network,
    *,
    prefix_v4: int = 32,
    prefix_v6: int = 128,
    allow_non_global: bool = False,
) -> list[PeerMapping]:
    mappings: dict[str, PeerMapping] = {}
    lines = [line for line in text.splitlines() if line.strip()]
    for line_number, line in enumerate(lines[1:], start=2):
        fields = line.split("\t")
        if len(fields) < 4:
            raise ValueError(f"invalid wg dump peer row at line {line_number}")
        public_key, endpoint, allowed_ips = fields[0], fields[2], fields[3]
        endpoint_ip = parse_endpoint_ip(endpoint)
        if endpoint_ip is None:
            continue
        if not allow_non_global and not endpoint_ip.is_global:
            continue
        ecs = endpoint_to_ecs(
            endpoint_ip,
            prefix_v4=prefix_v4,
            prefix_v6=prefix_v6,
        )

        for allowed_ip in allowed_ips.split(","):
            value = allowed_ip.strip()
            if not value or value == "(none)":
                continue
            try:
                source = ipaddress.ip_network(value, strict=False)
            except ValueError as exc:
                raise ValueError(
                    f"invalid AllowedIPs value at line {line_number}: {value}"
                ) from exc
            if source.version != wg_network.version or not source.subnet_of(wg_network):
                continue

            key = str(source)
            mapping = PeerMapping(source=source, ecs=ecs, public_key=public_key)
            previous = mappings.get(key)
            if previous and previous.ecs != mapping.ecs:
                raise ValueError(
                    f"conflicting endpoints for WireGuard source {source}: "
                    f"{previous.ecs} and {mapping.ecs}"
                )
            mappings[key] = mapping

    return sorted(
        mappings.values(),
        key=lambda item: (
            -item.source.prefixlen,
            item.source.version,
            int(item.source.network_address),
        ),
    )


def render_ecs_rules(mappings: Iterable[PeerMapping]) -> str:
    items = list(mappings)
    lines = [
        "-- AUTO-GENERATED by update-dnsdist-ecs.py. DO NOT EDIT.",
        f"-- active peer mappings: {len(items)}",
        "",
        "-- NetmaskGroupRule only accepts a NetmaskGroup object before dnsdist 1.9.",
        "local peerSourceNMG",
        "",
    ]
    for item in items:
        key_hint = item.public_key[:12] if item.public_key else "unknown"
        lines.extend(
            [
                f"-- peer {key_hint}...: {item.source} -> {item.ecs}",
                "peerSourceNMG = newNMG()",
                f'peerSourceNMG:addMask("{item.source}")',
                "addAction(",
                "  NetmaskGroupRule(peerSourceNMG),",
                "  SetECSOverrideAction(true)",
                ")",
                "addAction(",
                "  NetmaskGroupRule(peerSourceNMG),",
                f'  SetECSAction("{item.ecs}")',
                ")",
                "addAction(",
                "  NetmaskGroupRule(peerSourceNMG),",
                '  PoolAction("china-ecs")',
                ")",
                "",
            ]
        )
    lines.append("peerSourceNMG = nil")
    return "\n".join(lines)


def read_wg_dump(interface: str) -> str:
    try:
        result = subprocess.run(
            ["wg", "show", interface, "dump"],
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except subprocess.CalledProcessError as exc:
        detail = (exc.stderr or exc.stdout or "").strip()
        suffix = f": {detail}" if detail else ""
        raise RuntimeError(f"unable to inspect WireGuard interface {interface}{suffix}") from exc
    return result.stdout


def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate dnsdist ECS rules from WireGuard peer endpoints"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(os.getenv("DNSDIST_ECS_RULES", str(DEFAULT_TARGET))),
    )
    parser.add_argument(
        "--main-config",
        type=Path,
        default=Path(os.getenv("DNSDIST_MAIN_CONFIG", str(DEFAULT_MAIN_CONFIG))),
    )
    parser.add_argument(
        "--lock-file",
        type=Path,
        default=Path(os.getenv("DNSDIST_ECS_LOCK", str(DEFAULT_LOCK))),
    )
    parser.add_argument(
        "--dump-file",
        type=Path,
        help="read a saved 'wg show INTERFACE dump' result instead of invoking wg",
    )
    parser.add_argument("--no-check", action="store_true")
    parser.add_argument("--no-reload", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_argument_parser().parse_args(argv)
    interface = os.getenv("DNSDIST_WG_INTERFACE", "wg-pub")
    try:
        wg_network = ipaddress.ip_network(
            os.getenv("DNSDIST_WG_NETWORK", "10.133.0.0/24"),
            strict=False,
        )
        prefix_v4 = int(os.getenv("DNSDIST_ECS_PREFIX_V4", "32"))
        prefix_v6 = int(os.getenv("DNSDIST_ECS_PREFIX_V6", "128"))
        allow_non_global = env_bool("DNSDIST_ECS_ALLOW_NON_GLOBAL", False)
        dump = (
            args.dump_file.read_text(encoding="utf-8")
            if args.dump_file
            else read_wg_dump(interface)
        )
        mappings = parse_wg_dump(
            dump,
            wg_network,
            prefix_v4=prefix_v4,
            prefix_v6=prefix_v6,
            allow_non_global=allow_non_global,
        )
        content = render_ecs_rules(mappings)
        if args.dry_run:
            sys.stdout.write(content)
            return 0
        with exclusive_lock(args.lock_file):
            changed = activate_generated_file(
                args.output,
                content,
                args.main_config,
                check=not args.no_check,
                reload_service=not args.no_reload,
            )
    except Exception as exc:
        print(f"update-dnsdist-ecs: {exc}", file=sys.stderr)
        return 1

    print("ECS rules updated" if changed else "ECS rules unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
